let mijnVoornaam="Imran";
let mijnAchternaam="Kaouch";
let leeftijd="16";
let ikBenStemGerechtig="False";
let ikMagLegaalAlcoholKopen="False";
let ikMagBrommerRijden="True";
let SoftwareOntwikkeling="Mijn opleiding";
console.log(mijnVoornaam);
console.log(mijnAchternaam);
console.log(leeftijd);
console.log(ikBenStemGerechtig);
console.log(ikMagLegaalAlcoholKopen);
console.log(ikMagBrommerRijden);
console.log(SoftwareOntwikkeling); 